[package]
name = "pi-firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
gilrs = "0.11.1"
serde = { version = "1.0.228", features = ["derive"] }
serialport = "4.8.1"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
toml = "0.9.11"
